-- phpMyAdmin SQL Dump
-- version 5.1.3
-- https://www.phpmyadmin.net/
--
-- 主機： 127.0.0.1
-- 產生時間： 2022-05-14 14:55:37
-- 伺服器版本： 10.4.24-MariaDB
-- PHP 版本： 7.4.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- 資料庫: `437god`
--
CREATE DATABASE IF NOT EXISTS `437god` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE `437god`;

-- --------------------------------------------------------

--
-- 資料表結構 `fortune poems`
--

CREATE TABLE `fortune poems` (
  `poem_id` int(3) NOT NULL,
  `poem_no` varchar(6) COLLATE utf8_unicode_ci NOT NULL,
  `poem_url` varchar(3) COLLATE utf8_unicode_ci NOT NULL,
  `poem_sign` varchar(5) COLLATE utf8_unicode_ci NOT NULL,
  `poem_text` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `poem_meaning` mediumtext COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- 傾印資料表的資料 `fortune poems`
--

INSERT INTO `fortune poems` (`poem_id`, `poem_no`, `poem_url`, `poem_sign`, `poem_text`, `poem_meaning`) VALUES
(1, '第一支籤', '001', '大吉', '<h5 class=\"text-center tm-text-gray-dark\">七寶浮圖塔</h6><h6 class=\"text-center tm-text-gray\">就像出現了用美麗寶石做成的佛塔般地，似乎會有非常好的事情。</h6><h5 class=\"text-center tm-text-gray-dark\">高峰頂上安</h5><h6 class=\"text-center tm-text-gray\">因為能改用放眼萬事的立場，可以得到周圍的人們的信賴吧。</h6><h5 class=\"text-center tm-text-gray-dark\">眾人皆仰望</h5><h6 class=\"text-center tm-text-gray\">合乎正道的你的行為，能被很多人的認同及鼓勵。</h6><h5 class=\"text-center tm-text-gray-dark\">莫作等閒看</h5><h6 class=\"text-center tm-text-gray\">不用隨便的態度看事情，用正確的心思會招來更多的好的結果。</h6>', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會充分地實現吧。</span></div>\r\n<div class=\"mr-4 mb-2\"><span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治癒吧。</span></div><div class=\"mr-4 mb-2\"><span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">會出現吧。</span></div><div class=\"mr-4 mb-2\"><span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">變得遲遲地才找到吧。</span></div><div class=\"mr-4 mb-2\"><span class=\"tm-text-gray-dark\">蓋新居、搬家、嫁娶、旅行、交往等：</span><span class=\"tm-text-primary\">全部很好吧。</span></div><div class=\"mr-4 mb-2\"><span class=\"tm-text-gray-dark\">祝福語：</span><span class=\"tm-text-primary\">萬事行為謹慎。粗心大意行事的話，就會發生意想之外的災害吧。</span></div>'),
(2, '第二支籤', '002', '小吉', '<h5 class=\"text-center tm-text-gray-dark\">月被浮雲翳</h6>\r\n<h6 class=\"text-center tm-text-gray\">似乎抱著強烈的願望，但是照目前的樣子，似乎無法達成願望。</h6>\r\n<h5 class=\"text-center tm-text-gray-dark\">立事自昏迷</h5>\r\n<h6 class=\"text-center tm-text-gray\">因為光是想著要怎麼作，持續著沒有決心的情形。</h6>\r\n<h5 class=\"text-center tm-text-gray-dark\">幸乞隂公祐</h5>\r\n<h6 class=\"text-center tm-text-gray\">為了人而變得盡全力努力，幸福將會來到。</h6>\r\n<h5 class=\"text-center tm-text-gray-dark\">何慮不開眉</h5>\r\n<h6 class=\"text-center tm-text-gray\">似乎會有令人高興的事情發生。根據這件好事，不擔心未來的事也沒有關係了。</h6>', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">因為持續不斷地努力，必定會實現。</span>\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">雖然拖長，但是之後可以康復吧。</span>\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">遲遲地才出現吧。</span>\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">不能找出來吧。</span>\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">交往：</span><span class=\"tm-text-primary\">要節制吧。</span>\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">都不壞吧。</span>\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結親緣、旅行：</span><span class=\"tm-text-primary\">順利進行。</span>\r\n</div>'),
(3, '第三支籤', '003', '凶', '<h5 class=\"text-center tm-text-gray-dark\">愁惱損忠良</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">層層疊疊嘆氣與苦惱，被回報的事很少吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">青霄一炷香</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像向著天燒香祈禱般地，你的願望無法傳達天聽吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">雖然防小過</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">雖這樣說，但就算只有一點點善行也好，作了可以逃離災厄吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">閑慮覺時長</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">東想西想之間，似乎不知不覺就像過了很長的時間。等待時機的到來吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">難實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">雖然拖長，但是會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">要花很久的時間吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">難以找到吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">因為很壞，放棄吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">勉勉強強地算好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">要節制吧。</span>\r\n</div>'),
(4, '第四支籤', '004', '吉', '<h5 class=\"text-center tm-text-gray-dark\">累有興雲志</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">拼命地要出人頭地，可以看出你的志向。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">君恩祿未封</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">但是遺憾地是，你的不成熟還不能得到居上位者的認同。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">若逢侯手印</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">然而，就像是如果已經寫了好文章的話，就立刻得到認同般地，好好傳遞自己的心思是很重要的。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">好事始總總</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">好事也似乎會越來越接踵而起吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">能實現吧。如果這樣的話，終生幸福吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">變得遲遲地才會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">遲遲地才找到吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">途中要忍耐各式各樣的困難吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家、結親緣、交往：</span><span class=\"tm-text-primary\">萬事都好吧。</span>\r\n\r\n</div>'),
(5, '第五支籤', '005', '凶', '<h5 class=\"text-center tm-text-gray-dark\">家道未能昌</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就算試著努力家業，和努力相比卻難以繁盛起來吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">危危保禍殃</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">不是一生災禍，只是危險的事比較多而已吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">暗雲侵月桂</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像烏雲遮月一樣，一生阻礙比較多吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">佳人一炷香</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">在身份高貴的婦人房裡，各種想法像香一樣擴散開來般，心裡無法平靜吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">難以實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">難治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">不會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">難找到吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">先放棄，暫時觀察情況再說吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結親緣、旅行、交往：</span><span class=\"tm-text-primary\">因為萬事兇惡，請諸行為慎重行事。</span>\r\n\r\n</div>'),
(6, '第六支籤', '006', '末吉', '<h5 class=\"text-center tm-text-gray-dark\">宅墓鬼凶多</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">家中恐怕有災禍。行為慎重，抱著深深的信心，這樣可以帶來好的結果。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">人事有爻訛</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">個人的問題或遭遇，過錯或過失很多，事情難以進展吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">傷財防損失</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就算破財，也會有所得。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">祈福始中和</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">因為竭盡祈求神佛的力量，自己盡力努力，能到幸福吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">難以實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">康復很花時間吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">遲遲地才出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">難找到吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結親緣、交往：</span><span class=\"tm-text-primary\">壞吧。</span>\r\n\r\n</div>'),
(7, '第七支籤', '007', '凶', '<h5 class=\"text-center tm-text-gray-dark\">登舟待便風</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像風不吹船無法前進一樣，就算採取行動也難以向前發展吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">月色暗矇矓</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像月亮被烏雲籠罩著，前後都無法看見一樣，對事情，似乎作一些莽撞的行為。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">遇碾香輪去</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">為了逃離災難，想請託別人教導怎麼作，但是況狀似乎變得很困難。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">高山千萬重</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">但是現在還是靜靜的過生活吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">難以實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">難以治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">不會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">難以找到吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">換時間吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結親緣、喜慶祝賀、旅行、交往：</span><span class=\"tm-text-primary\">不好吧。</span>\r\n\r\n</div>'),
(8, '第八支籤', '008', '大吉', '<h5 class=\"text-center tm-text-gray-dark\">勿頭中見尾</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">在腦海裡沒有對失敗或結果的恐懼，抬頭挺胸地朝著目標達成而努力吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">文華須得理</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">無論是文學或武術都能得到真理，要有充實自己的心態吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">禾刀自偶然</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像用刀來割稻般地，會得到成果，幸福會自然地到來吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">當遇非常喜</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">如果正心地守道的話，可以變得幸福吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治好。請注意養生吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">可以找到吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家、交往：</span><span class=\"tm-text-primary\">是好事吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">途中請不要粗心大意吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結親緣：</span><span class=\"tm-text-primary\">全都是好的吧。</span>\r\n\r\n</div>'),
(9, '第九支籤', '009', '大吉', '<h5 class=\"text-center tm-text-gray-dark\">有名須得遇</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">按照所想的，夢想實現，名聲也廣傳人間吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">三望一朝遷</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像三個願望可以完全的實現般地，全部能一次完全的被實現吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">貴人來指處</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">從比自己身份地位高的人，給予各式各樣令人欣喜的事吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">華菓應時鮮</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是隨著四季循環花會開、會結果一樣，每天努力會有成果，好運會展開吧。 </h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會找到吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">沒問題吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結親緣、交往：</span><span class=\"tm-text-primary\">全都好吧。</span>\r\n\r\n</div>'),
(10, '第十支籤', '010', '大吉', '<h5 class=\"text-center tm-text-gray-dark\">舊用多成破</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">過去的不幸或許多煩惱也會消去，好事將發生吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">新更始見財</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">隨著新的願望的出現，財富也會增加。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">改求雲外望</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像是在雲上追求願望般地，請試著追求高高的願望。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">枯木遇春開</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像枯木在春天開花一樣，一定會變得很繁盛吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">立刻會找到吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">會變為好結果吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結親緣、旅行、交往：</span><span class=\"tm-text-primary\">全部變為好結果吧。</span>\r\n\r\n</div>'),
(11, '第十一支籤', '011', '大吉', '<h5 class=\"text-center tm-text-gray-dark\">有祿興家業</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">幸福與收入具足，家業也漸漸繁盛起來吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">文華達帝都</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">才能顯現出來，可得世人的好評價吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">雲中乘好箭</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就算是向空中放箭也可以得到好的獵物般地，任何事也都可以成功吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">兼得貴人扶</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">得到這樣的幸福之外，加上還可以得到居上位者或神佛的幫助吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會充分地實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會找到吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">沒問題吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">全部都能得到好結果吧。</span>\r\n\r\n</div>'),
(12, '第十二支籤', '012', '大吉', '<h5 class=\"text-center tm-text-gray-dark\">楊柳遇春時</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像柳樹也逢春增添綠色般地，希望也會出現吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">殘花發舊枝</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像老枝也發芽，開花般地，喜事會到來吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">重重霜雪裡</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像在重重霜或雪中般地，無論怎樣過去的勞苦不斷吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">黃金色更輝</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">但是像黃金色無論到何時，都閃亮耀眼般地，不要忘以前的勞苦，用誠實的心過生活吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會變好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">晚出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會回來吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">會成為好結果吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">沒有阻礙吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">全都適當吧。</span>\r\n\r\n</div>'),
(13, '第十三支籤', '013', '大吉', '<h5 class=\"text-center tm-text-gray-dark\">手把大陽輝</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">如果時機來到的話，抱著勇氣努力做事，可以過著充實的生活吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">東君發舊枝</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像是老枝條，隨著春天到來，花就開了一樣，運勢會開展吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">稼苗方欲秀</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像稻苗也是如果春天來了的話，就會生長般地，你也會繁榮昌盛吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">猶更上雲梯</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是也能爬上難登的雲梯般，因為更加地持續努力就會成功吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">立刻找就能找到吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">在春天和夏天好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">全部都好吧。</span>\r\n\r\n</div>'),
(14, '第十四支籤', '014', '末吉', '<h5 class=\"text-center tm-text-gray-dark\">玉石未分時</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像是就算有寶玉，哪一個是寶石哪一個是石頭還分不清楚般地，沒辦法分辨事物的狀況。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">憂心轉更悲</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就算是想要出人頭地，但會為了各式各樣的事情而心痛、嘆息、悲傷也說不定。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">前途通大道</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">如果忍耐勞苦，將來自然地看得到未來的去向吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">花發應殘枝</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">然後像枯枝開花般地，願望會實現吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">很花時間但會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會拖長吧，但是不會影響性命吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">似乎會變得遲吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">難出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">不太好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行、交往：</span><span class=\"tm-text-primary\">避開吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚：</span><span class=\"tm-text-primary\">現在要節制，如果往後的話好吧。</span>\r\n\r\n</div>'),
(15, '第十五支籤', '015', '凶', '<h5 class=\"text-center tm-text-gray-dark\">年乖數亦孤</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">朋友年年地減少，變成孤單一人，生活變得不自由吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">久病未能蘇</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">長期的疾病雖然種種地想治癒，但是卻康復無望吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">岸危舟未發</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像船想靠岸，因為危險不能靠岸般地，想做點什麼，但是因為有阻礙，總是不能著手進行吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">龍臥失明珠</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是龍失去重要的龍珠般地，人也失去希望吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">難以實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">危險吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">不會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">難找回吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">都不好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行、結親緣：</span><span class=\"tm-text-primary\">壞吧。</span>\r\n\r\n</div>'),
(16, '第十六支籤', '016', '吉', '<h5 class=\"text-center tm-text-gray-dark\">破改重成望</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">拋開至今為止的願望，期待別的願望為佳吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">前途喜亦寧</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">要前往的目的地有令人欣喜的事，變為安穩的心情吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">貴人相助處</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">因為得到居上位者（觀世音菩薩）的幫助，越來越得到力量吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">祿馬照前程</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是用馬載著上天給予的寶物，前方光明照耀般地，在人世間地位或收入等也和想的一樣地充滿吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">能被實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會康復吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">會來吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">會有好結果吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結親緣、交往：</span><span class=\"tm-text-primary\">全部會變成好結果吧。</span>\r\n\r\n</div>'),
(17, '第十七支籤', '017', '凶', '<h5 class=\"text-center tm-text-gray-dark\">怪異防憂惱</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">如果作一些想要防止降落在自己身上的危險的事的話，反而煩惱似乎變多了。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">人宅見分離</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">不知不覺間，不好的事情持續著，似乎會有家人分離的事。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">惜華還值雨</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像捨不得花凋謝的話，更是會被雨淋凋萎般地，不好的是似乎持續著。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">杯酒惹閑非</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">因為無法按照所想的發展，沈溺於喝酒之類的，似乎還是會產生壞想法吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">難實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">康復需要長時間吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">不會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">不會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">先放棄，暫時觀察情況再說吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">似乎引起壞的結果吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">婚事、交往：</span><span class=\"tm-text-primary\">全部不好吧。</span>\r\n\r\n</div>'),
(18, '第十八支籤', '018', '吉', '<h5 class=\"text-center tm-text-gray-dark\">離暗出明時</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像烏雲的天空也漸漸地晴朗，可以看到月亮般地，今後漸漸地希望能被實現吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">麻衣變綠衣</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像脫掉破舊的衣服，穿著漂亮的衣服般地，用全新的心情做好每天的善行吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">舊憂終是退</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">長時間的悲傷也漸漸地消散吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">遇祿應交輝</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">福德自然地增加，人生光輝閃耀吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會實踐吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結親緣：</span><span class=\"tm-text-primary\">全部變為好結果吧。</span>\r\n\r\n</div>'),
(19, '第十九支籤', '019', '小吉', '<h5 class=\"text-center tm-text-gray-dark\">家道生荊棘</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">家裡的生意有阻礙，事情不按照所想地進行吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">兒孫防虎威</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">子或孫如果常聽長輩（居上位者）的話，就會沒事吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">香前祈福厚</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">抱持著強烈的信心，如果竭盡真誠的心的話，將來會有好事吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">方得免分離</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">得到福德，本來別離的命運的人（物）會在不用分別的情況下解決吧。 </h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">能實現一半吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">雖然長期得病，但是不會危及性命吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">變成遲遲地出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">大概找不回來了吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">不好也不壞吧。 </span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">節制比較好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">交往：</span><span class=\"tm-text-primary\">節制吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚：</span><span class=\"tm-text-primary\">不會到達好的結果吧。</span>\r\n\r\n</div>'),
(20, '第二十支籤', '020', '吉', '<h5 class=\"text-center tm-text-gray-dark\">月出漸分明</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是月亮也出來了，漸漸地變明朗般地，終於漸漸地希望也能被實現吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">家財每每興</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">家中的財產也能慢慢地累積，家中的生意也會繁盛起來吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">何言先有滯</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">至今為止不能暢快地運作的事情，最後也會向好的方面進行吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">更變立功名</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">更進一步地，世間的評價好，變得能得到利益吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">能被實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">會來吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">全部都得到好結果吧。</span>\r\n\r\n</div>'),
(21, '第二十一支', '021', '吉', '<h5 class=\"text-center tm-text-gray-dark\">洗出經年否</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是至今為止的壞事已被洗去般地，變成輕鬆暢快的狀況吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">光華得再清</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">好事再度發生，更加地帶來比現在更好的結果吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">所求終吉利</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">願望都會變成好結果吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">重日照前程</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">隨著日子一天又一天的過，前途增添光輝，狀況也變好吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">能被實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">雖然會恢復但是切忌粗心大意。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚：</span><span class=\"tm-text-primary\">會得到好結果吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行、交往：</span><span class=\"tm-text-primary\">全部好吧。</span>\r\n\r\n</div>'),
(22, '第二十二支', '022', '吉', '<h5 class=\"text-center tm-text-gray-dark\">漸漸濃雲散</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像濃雲漸漸變無，萬里晴空般地，問題也解決，似乎好事會發生。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">看看月再明</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像月亮再出現，於澄凈的天空放光明般地，心情也輕鬆吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">逢春華菓秀</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像草木在春天生氣勃勃，花也盛開而變得色彩繽紛般地，過著充實的生活，也變得幸福吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">雨過竹重青</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像竹子也遇雨增添色彩般，如果人也連連遇好事的話，越來越能得到好結果吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">雖然能被實現，但是變得比較晚吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">因為會治好，耐心等待康復吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">雖然會出現但很遲吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、旅行、交往：</span><span class=\"tm-text-primary\">全都好吧。</span>\r\n\r\n</div>'),
(23, '第二十三支', '023', '吉', '<h5 class=\"text-center tm-text-gray-dark\">紅雲隨步起</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">已經能看到好的徵兆。要前往的將來會遇到好事吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">一箭中青霄</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">你也像向青空射出的箭般地作吧。這樣的話，無論什麼願望也都沒問題，會實現吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">鹿行千里遠</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">但是受到眼前的成功的影響驕傲自大的話，就會變得看不到目標吧。通盤的判斷然後行動是很重要的吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">爭知去路遙</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">因為過於自信會招致失敗，小心期望過高，誠實是很重要的事。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">雖然會實現，但是要考慮能力吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">難以康復吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">不能出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">難以找到吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">沒問題吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>'),
(24, '第二十四支', '024', '凶', '<h5 class=\"text-center tm-text-gray-dark\">三女莫相逢</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">產生不合道理的慾望等等的事，請不要做身為人不可以犯的錯誤行為吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">盟言說未通</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">光只是口頭約束，沒有實行的話，就會與對方心意無法相通。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">門裡心肝掛</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">因此，煩惱、苦悶也是不行的。抱持著信仰心吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">縞素子重重</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">不這樣的話，只會發生不吉利的事吧。因此從各種面向，好好地分辨黑白是非吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">不會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">雖然拖很長，但會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">不能出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">變成到後來才找到吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">不好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">不好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">變成不好的結果吧。</span>\r\n\r\n</div>'),
(25, '第二十五支', '025', '吉', '<h5 class=\"text-center tm-text-gray-dark\">枯木逢春生</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像草木在春天發芽，綠葉生長茂盛般地，隨著時間繁榮昌盛吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">前途必利亨</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">去路必有好事發生，能幸福吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">亦得佳人箭</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">能邂逅很棒的人吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">乘車祿自行</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">變得能得到崇高地位、財產吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">遲遲才來吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">似乎沒問題。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行、結親緣：</span><span class=\"tm-text-primary\">全部都變成好結果吧。</span>\r\n\r\n</div>'),
(26, '第二十六支', '026', '吉', '<h5 class=\"text-center tm-text-gray-dark\">將軍有異聲</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">平日的指導力得到部下的信賴，大家聽你的指揮吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">進兵萬里程</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像是無論在多遠的人都尊崇將軍的命令，大批士兵向前行進般地，即使多麼困難的工作都能得到身邊的人或部下的幫助吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">爭知臨敵處</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">但是，努力急著成功都徒勞無功吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">道勝却虛名</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就算是達成了目標，也會變成白費力氣吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">會變成好結果吧。</span>\r\n\r\n</div>'),
(27, '第二十七支', '027', '吉', '<h5 class=\"text-center tm-text-gray-dark\">望祿應重山</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像要越過重重相連的山脈般，因為克服辛勞又痛苦的事，沒多久就能得到上天給予的幸福吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">花紅喜悅顏</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像紅色美麗的花朵已經綻放般的喜悅充滿臉上吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">舉頭看皎月</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像如果看到月亮的話，雲也消散了，清澈地能看到般地，變成是在人生上能夠發揮能力的時期吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">漸出黑雲間</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像終於從又厚又黑的雲中脫離般地，痛苦與煩惱的每天過去了，圍繞而來是沈靜安心的心情吧。但是，請多加注意，切忌粗心大意。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治好吧，但切忌粗心大意。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">非常好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">全部都變成好結果吧。</span>\r\n\r\n</div>'),
(28, '第二十八支', '028', '凶', '<h5 class=\"text-center tm-text-gray-dark\">意速無船渡</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是就算心裡很著急，船卻不前進般地，只是焦急，事情沒有改變吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">波深必誤身</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是就算想勉強渡過海洋或河川，波浪又高又危險般地，就算想快點到達目的地貫徹事情，卻反而變成自己綁著自己的脖子的結果吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">切須回舊路</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">想在異鄉出人頭地，不如回到故鄉靜靜地生活比較好吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">方可免災迍</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">如果這樣的話，有災害也能逃離吧，自己也會變得安泰吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">難以實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">如果長期養生的話會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">變得遲遲地才出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">難出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">壞吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">壞吧。</span>\r\n\r\n</div>'),
(29, '第二十九支', '029', '吉', '<h5 class=\"text-center tm-text-gray-dark\">憂轗漸消融</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">悲傷或擔心的事終於消失了吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">求名得再通</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">如果想聲名遠播的話，能像以前一樣再次向身邊的人傳播名聲吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">寶財臨祿位</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">收入或地位也變成如同希望一樣實現吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">當遇主人公</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">能遇到好的長官，慢慢地向成功邁進吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">能被實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。 </span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">交往、結婚：</span><span class=\"tm-text-primary\">全都好吧。</span>\r\n\r\n</div>'),
(30, '第三十支籤', '030', '吉', '<h5 class=\"text-center tm-text-gray-dark\">仙鶴立高枝</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就算吉利的鶴想停在高高的樹枝上，沒辦法到達般地，雖有強烈的願望但阻礙很多吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">防他暗箭虧</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像在黑暗的夜晚中，要難防範不知從哪飛來的箭般地，困難是能想像得到的吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">井畔剛刀利</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就算鶴站在泉水中，因為有又硬又銳利的刀子，似乎有危險般地，似乎要發生很多妨礙、阻礙的事吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">戶內更防危</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">不單單只是外面的事，家裡的危機也是不擔心不行。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">難實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">危險吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">不會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">難出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">如果能祈求神佛的保佑，會變成勉強可以的結果吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">壞吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">節制吧。</span>\r\n\r\n</div>'),
(31, '第三十一支', '031', '末吉', '<h5 class=\"text-center tm-text-gray-dark\">鯤鯨未變時</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">因為鯤鯨是很大的魚，不知不覺會變成大鳥。但是，因為現在尚未變化，一直抱著很大的希望，但是還不能實現的狀態吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">且守碧潭溪</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像暫時守著深青色的溪流中，等待時機的到來般地，現在天天的行動都要保守，等待幸運的到來吧。這麼做的話，時來運轉，變成大鳥的時候會到來吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">風雲興巨浪</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">掀起浪花，有著向天空飛去的沸騰的心。幸運到來，朝向成功，拼命地不斷努力是很重要的。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">一息過天涯</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">這樣做就會一口氣飛向天空吧。步向成功的道路，在世間似乎會好名聲遠播的事。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">雖能被實現，但要考慮時機吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">拖很久吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">變得遲遲地才出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">變得遲遲地才出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">沒阻礙吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>'),
(32, '第三十二支', '032', '吉', '<h5 class=\"text-center tm-text-gray-dark\">似玉藏深石</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像是不知道寶石藏深在石頭下般地，就算有才能，不在意，不努力振作施展才能的話，什麼都不能得到吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">休將故眼看</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">用不管眼前事物的方式，才能是會就這樣埋沒下去吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">一朝良匠別</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">可是如果不斷持續地努力的話，不知不覺能被良師、益友發現。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">方見寶光寒</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">然後，就像被磨光的寶石閃閃發光地出現般，能展現成果，能為社會盡心力吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">雖然會拖長，但是不會失去生命。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">變得遲遲地才出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">全部和好結果有關吧。</span>\r\n\r\n</div>');
INSERT INTO `fortune poems` (`poem_id`, `poem_no`, `poem_url`, `poem_sign`, `poem_text`, `poem_meaning`) VALUES
(33, '第三十三支', '033', '吉', '<h5 class=\"text-center tm-text-gray-dark\">枯木逢春艷</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就算是枯木也會在春天開出美麗的花朵般地，人生就算是在嚴長的冬天裡的辛勞，有一天會得到回報吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">芳菲再發林</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是草花再次盛開，氣味也充滿林間般地，幸運再次來的時節吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">雲間方見月</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是雲散可以看見明月般地，各式各樣的困難或痛苦之間，幸運會到來吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">前遇貴人欽</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">善人（神佛、人生的前輩）的引導，漸漸地喜事增加吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">能被實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">沒有阻礙吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">全都好吧。</span>\r\n\r\n</div>'),
(34, '第三十四支', '034', '吉', '<h5 class=\"text-center tm-text-gray-dark\">臘木春將至</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是冬天枯萎的樹木也會有花開的春天接近般地，人生的苦難也結束，慢慢地運氣會到來吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">芳菲喜再新</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是如果春天來了的話草木也發新芽，吐芬芳，開滿花般地，能發揮才能吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">鯤鯨興巨浪</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">讓人看到大魚變成大鳥，掀起大波浪的氣勢，去推動事情吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">舉鉤祿為真</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是如果要釣魚的話就能大豐收般地，因為窮究真正的道路，你成功的時候也會到來吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">能被實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">遲吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">遲遲才出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">全都和好結果相連吧。</span>\r\n\r\n</div>'),
(35, '第三十五支', '035', '吉', '<h5 class=\"text-center tm-text-gray-dark\">射鹿須乘箭</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像拉弓瞄準，就能按照所想地射中鹿一樣，自己的行為直接連向成功的方向吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">故僧引路歸</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像被良好的引導引領般地，能得到良好的居上位者援助和意見吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">遇道同仙籍</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">因為遵從有智慧的人的教導，能夠得到出人頭地的喜悅吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">光華映晚暉</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是花在夕陽的照耀下，越來越閃耀般地，在周圍的人對你的評價變高了吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">能被實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">變遲才出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">沒有障礙吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行、結婚、交往：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>'),
(36, '第三十六支', '036', '末吉', '<h5 class=\"text-center tm-text-gray-dark\">先損後有益</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">即使開始的時候損失，後來一定能得到利益的，有令人高興的事吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">如月之剝蝕</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就算月亮變小，也會再變大，變回原來的滿月般地，雖然希望變薄弱了，但後來能被實現吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">玉兔待重生</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">雖然變成日食或月食的話，世界就變得黑暗，但是時間經過，馬上就回到原來的狀況。災難也隨時間過去，願望會實現吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">光華當滿室</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">月亮的光芒（希望）照進家中，變得明亮般地，充滿歡喜吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">稍後會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">雖然拖長，但可以治癒吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">遲遲地才出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">難出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">應該先放棄，暫時多觀察情況再說吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">途中，似乎會有不好的事吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結親緣、喜慶、交往：</span><span class=\"tm-text-primary\">不好吧。</span>\r\n\r\n</div>'),
(37, '第三十七支', '037', '半吉', '<h5 class=\"text-center tm-text-gray-dark\">陰靉未能通</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像烏雲又厚又長，分不清東西般地，心裡迷惘，現在願望還無法上達天聽吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">求名亦未逢</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">雖然祈求名聞人世間，但是現在還沒遇到機會吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">幸然須有變</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">可是心中的痛苦離去，運勢展開，變得幸福的日子會來了吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">一箭中雙鴻</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是用一支箭射中兩隻鳥般地，好事似乎接踵而來。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">難以實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">變成遲遲地才好轉吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">變成遲遲地才出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">變成遲遲地才出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">往後一點，變成好吧。</span>\r\n\r\n</div>'),
(38, '第三十八支', '038', '半吉', '<h5 class=\"text-center tm-text-gray-dark\">月照天書靜</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是天空沒有陰霾明顯地能看見月亮般地，沒有迷惘，澄淨的心吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">雲生霧彩霞</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">但是，至今為止看到的月亮也有雲靄，心裡也產生迷惘吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">久想離庭客</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">和親密的友人分別，暫時心沈浸在悲傷的思緒中吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">無事惹咨嗟</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">雖然沒事，但是卻因為擔心悲嘆的事很多，轉換心情吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">難實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會拖長吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">不會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">難出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">先放棄，暫時觀察情況再說吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">先放棄，暫時觀察情況吧。</span>\r\n\r\n</div>'),
(39, '第三十九支', '039', '凶', '<h5 class=\"text-center tm-text-gray-dark\">望用方心腹</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就算有願望也只是心裡想想而已，還沒到達要付諸行動吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">家鄉被火災</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像有家裡燒起來般地災難，接踵而來的危險。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">憂危三五度</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">悲傷或危險的事再次地持續發生吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">由損斷頭財</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">因為有失去和生命一樣重要的東西的可能，要小心謹慎吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">難以實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">又壞又危險吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">不會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">難出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">避開比較好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">不好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">交往、結婚：</span><span class=\"tm-text-primary\">招致壞結果吧。</span>\r\n\r\n</div>'),
(40, '第四十支籤', '040', '末小吉', '<h5 class=\"text-center tm-text-gray-dark\">中正方成道</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">正因為什麼事都不偏頗的中正之道的正確行為，能夠消除災難吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">姦邪恐惹愆</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">一有邪念的話就會被引入壞的方向而去吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">壺中盛妙藥</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像是在藥箱中先存放著有效的藥般，不迷失去自己地珍惜真誠心吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">非久去煩煎</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">這樣做的話煩惱就會離去，災難會消去吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">難以立刻地實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">雖然拖長但會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">變成遲遲才地出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">不好也不壞吧。</span>\r\n\r\n</div>'),
(41, '第四十一支籤', '041', '末吉', '<h5 class=\"text-center tm-text-gray-dark\">有物不周旋</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">雖然有很多東西但是難到手的狀況。雖然希望很豐富，但是難以實現吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">須防損半邊</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">成功一半，損失一半吧。但是不要堅持小事，想著一半已經成功事吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">家鄉煙火裡</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">有火災發生的危險。要充分地注意吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">祈福始安然</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">相信神明或佛菩薩，如果抱著堅定的心，最後會變得安泰吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">難以實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會拖長吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">變成遲遲地才出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">難出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">不好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">途中似乎有不好的事。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">會產生不好的結果吧。</span>\r\n\r\n</div>'),
(42, '第四十二支籤', '042', '吉', '<h5 class=\"text-center tm-text-gray-dark\">桂華春將到</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是桂花在春天飄香般地，對你也變成是運勢展開的時機吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">雲天好進程</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">人也轉運的話，有得到崇高的地位與榮譽的機會。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">貴人相遇處</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">有觀世音菩薩或有力人士的引導吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">暗月再分明</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">如陰天的月亮放晴般地，越來越會發生好事吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治癒吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">變得遲遲地才出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">全都會變成好結果吧。</span>\r\n\r\n</div>'),
(43, '第四十三支籤', '043', '吉', '<h5 class=\"text-center tm-text-gray-dark\">月桂將相滿</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像月缺不久將變成滿月般地，好運全盛的時期正在接近了。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">追鹿映山溪</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">鹿就是祿。也就是說，雖然現在還沒得到崇高的地位和收入，但是有將來會得到的命運。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">貴人乘遠箭</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">箭就是弓箭。應該要尊敬的人從遠方乘箭而來的援助之暗示是表示著如果學習這個人的善行而做的話，表示能得到崇高地位與收入。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">好事始相宜</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">願望開始實現，名聲被好好地知道，會變得幸福吧。但是切忌高傲自滿。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">雖然拖長但是會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">變成遲遲地才出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">難出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">變成好結果吧。</span>\r\n\r\n</div>'),
(44, '第四十四支籤', '044', '吉', '<h5 class=\"text-center tm-text-gray-dark\">盤中黑白子</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像在下圍棋當中的輸贏一樣，人生的吉或凶也還沒確定吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">一著要先機</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">勝負的事或人生都是要取得先機比什麼都還重要吧。區別善惡，如果是善道的話，筆直地著向善道而去是好的吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">天龍降甘澤</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">神明或佛菩薩會降下甘露（恩惠）的援助吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">洗出舊根基</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">用甘露水洗去過去的罪惡般地，清澈地，變成可以發揮本來的能力吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治癒吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">變成遲遲地才出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">沒問題吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">全都好吧。</span>\r\n\r\n</div>'),
(45, '第四十五支籤', '045', '吉', '<h5 class=\"text-center tm-text-gray-dark\">有意興高顯</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">受到別人的信賴，得到名聲，變成能夠累積財富吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">祿馬引前程</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">如果能一直保持著善心的話，在將來的人生幸運會成為你的嚮導吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">得遇雲中箭</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">因為令人感謝的神佛的加護，會遇到幸運吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">芝蘭滿路生</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">如藥草或香草一片茂盛般地，被好人包圍，名聲在世間被知道，能夠變得幸福吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">變遲遲地才出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">遲遲地才出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">全都好結果相連吧。</span>\r\n\r\n</div>'),
(46, '第四十六支籤', '046', '凶', '<h5 class=\"text-center tm-text-gray-dark\">雷發震天昏</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">在烏雲裡雷聲響遍，變得像是要震撼天地般地，是非常令人擔心的狀況。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">佳人獨掩門</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">少女獨自一人，沒和人交流，孤單地的狀況。要時時警戒吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">交加文書上</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">在合約等事情，似乎會發生錯誤或訴訟。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">無事也遭迍</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">雖然說如果誠心誠意地小心謹慎的話比較好，但是過度信任自己的才能，打算做什麼行動的話就全部會變成為凶。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">難以實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">不會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">難出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">現在放棄吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">在途中有不好的事吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結親緣、喜慶、交往：</span><span class=\"tm-text-primary\">會產生不好的結果吧。</span>\r\n\r\n</div>'),
(47, '第四十七支籤', '047', '吉', '<h5 class=\"text-center tm-text-gray-dark\">更望身前立</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">雖然為了早點實現願望似乎一直期待著，但是不可以過度著急。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">何期在晚成</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是大器晚成般地，延長志氣，擴大心胸，不焦急慢慢地等待成功吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">若遇重山去</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">重山是一山又一山的意思。因為辛苦地越過人生的山坡，希望也變得可以實現。必定會成功吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">財祿自相迎</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">財產和地位也變得可以到手吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">變成往後才會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">變得遲遲才出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">在將來似乎有好事吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">全部都可得到好結果吧。</span>\r\n\r\n</div>'),
(48, '第四十八支籤', '048', '小吉', '<h5 class=\"text-center tm-text-gray-dark\">見祿隔前溪</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是隔著山谷看得見寶物般地，就算想要的東西就在眼前，似乎也難得到吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">勞心休更迷</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">勉強地想得到那個財寶，會使心裡迷惘，放棄吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">一朝逢好渡</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就這樣用平常心按照平日的生活吧。如果時機來的話，自然會得到財寶。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">鸞鳳入雲飛</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">有居上位者或認識的人的援助吧。像鳳凰飛向天空般地，會出人頭地，好事會來臨吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">如果一直抱持著正直的心的話，到後來能被實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">雖然拖長，但將來會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">變成遲遲才來吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">雖然開始不好，但是到後來會變好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行、結婚、交往：</span><span class=\"tm-text-primary\">馬馬虎虎吧。</span>\r\n\r\n</div>'),
(49, '第四十九支籤', '049', '吉', '<h5 class=\"text-center tm-text-gray-dark\">正好中秋月</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是十五號的夜晚，沒有月缺，又圓又明亮的月亮般地，運氣非常好吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">蟾蜍皎潔間</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">就像因為月亮皎潔，住在裡面的兔子和蟾蜍能清楚看見般地，展現潔淨的心和光輝吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">暗雲知何處</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">像是天空一點雲都沒有，萬里晴空般地，沒有妨礙的東西，心中也沒有迷惘吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">故故兩相攀</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">整個天空沒有雲般地，心中沒有比這個更澄淨的吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">嚴重吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">變成遲遲才出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">難出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">馬馬虎虎吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">交往、結婚：</span><span class=\"tm-text-primary\">馬馬虎虎吧。</span>\r\n\r\n</div>'),
(50, '第五十支籤', '050', '吉', '<h5 class=\"text-center tm-text-gray-dark\">有達宜更變</h6>\r\n\r\n<h6 class=\"text-center tm-text-gray\">為了達成事情，要好好地理解那件事的內容，邊改進以前的方法，邊向前進吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">重山利政逢</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">如果山重疊的話，成為出這個字。已經下了使事情達成的決心的話，從現在的地方起飛展開行動吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">前途相偶合</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">這麼做的話，在將來自然而然地能遇見幸福吧。</h6>\r\n\r\n<h5 class=\"text-center tm-text-gray-dark\">財祿保亨通</h5>\r\n\r\n<h6 class=\"text-center tm-text-gray\">再來，財寶也從一開始到結束確實地能得到吧。</h6>\r\n', '<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">願望：</span><span class=\"tm-text-primary\">會實現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">疾病：</span><span class=\"tm-text-primary\">會治好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">盼望的人：</span><span class=\"tm-text-primary\">變遲吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">遺失物：</span><span class=\"tm-text-primary\">會出現吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">蓋新居、搬家：</span><span class=\"tm-text-primary\">好吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">旅行：</span><span class=\"tm-text-primary\">成為好的旅行吧。</span>\r\n\r\n</div>\r\n<div class=\"mr-4 mb-2\">\r\n<span class=\"tm-text-gray-dark\">結婚、交往：</span><span class=\"tm-text-primary\">成為好的結果吧。</span>\r\n\r\n</div>');

-- --------------------------------------------------------

--
-- 資料表結構 `member`
--

CREATE TABLE `member` (
  `member_id` int(20) NOT NULL,
  `member_name` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `member_email` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `member_password` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `member_level` varchar(5) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- 傾印資料表的資料 `member`
--

INSERT INTO `member` (`member_id`, `member_name`, `member_email`, `member_password`, `member_level`) VALUES
(10001, '王曉明', 'S0861126@gamail.com', 'aaaaaa', '初級'),
(10002, '張小飛', 'S086112@gamail.com', 'bbbbb', '中級'),
(10003, '陳大華', '21S86126@gamail.com', 'ccccc', '高級'),
(10004, '蔡依林', 'daa26@gamail.com', 'ddddd', '中級'),
(10005, '周杰倫', 'apple@gamail.com', 'fffff', '初級'),
(10006, 'member', 'adddddf@gamail.com', 'member123456', '初級');

-- --------------------------------------------------------

--
-- 資料表結構 `order`
--

CREATE TABLE `order` (
  `member_id` int(20) NOT NULL,
  `order_id` int(20) NOT NULL,
  `order_price` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- 傾印資料表的資料 `order`
--

INSERT INTO `order` (`member_id`, `order_id`, `order_price`) VALUES
(10002, 1, 80),
(10003, 2, 160),
(10004, 3, 85),
(10006, 4, 240);

-- --------------------------------------------------------

--
-- 資料表結構 `order_content`
--

CREATE TABLE `order_content` (
  `order_id` int(20) NOT NULL,
  `product_name` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `product_categories` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `product_numbers` int(20) NOT NULL,
  `product_price` int(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- 傾印資料表的資料 `order_content`
--

INSERT INTO `order_content` (`order_id`, `product_name`, `product_categories`, `product_numbers`, `product_price`) VALUES
(1, '考試御守', '御守', 1, 80),
(2, '戀愛御守', '御守', 2, 160),
(3, '求籤', '紀念品', 2, 200),
(4, '刮痧板', '佛具', 1, 180);

-- --------------------------------------------------------

--
-- 資料表結構 `products`
--

CREATE TABLE `products` (
  `product_id` int(11) NOT NULL,
  `product_picture` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `product_name` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `product_categories` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `product_price` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `product_type` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `product_instruction` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- 傾印資料表的資料 `products`
--

INSERT INTO `products` (`product_id`, `product_picture`, `product_name`, `product_categories`, `product_price`, `product_type`, `product_instruction`) VALUES
(1, 'img/portfolio/a1.png', '考試御守', '御守', '80', '<option>藍色</option>\r\n<option>紅色</option>', '在日本，御守是愿望的象征。御守最早用來辟邪和解除厄運，逐漸衍生到交通安全、安產、良緣、學業、健康等方面。現在，日本人尤其是女性每年都會購買更換御守，大家都用他來饋贈親朋以表達自己的祝愿，或是寄托希望、緩解壓力等等。所有商品百分百日本工藝，面料為日本京都名織物-金襴，手工精細，目前為止國內的廠家只能模仿花型及圖案，而金襴本身是無法模仿的哦。'),
(2, 'img/portfolio/a2.png', '戀愛御守', '御守', '80', '<option>粉紅色</option>\r\n<option>淺藍色</option>', '在日本，御守是愿望的象征。御守最早用來辟邪和解除厄運，逐漸衍生到交通安全、安產、良緣、學業、健康等方面。現在，日本人尤其是女性每年都會購買更換御守，大家都用他來饋贈親朋以表達自己的祝愿，或是寄托希望、緩解壓力等等。所有商品百分百日本工藝，面料為日本京都名織物-金襴，手工精細，目前為止國內的廠家只能模仿花型及圖案，而金襴本身是無法模仿的哦。'),
(3, 'img/portfolio/a3.png', '健康御守', '御守', '80', '<option>粉紅色</option>\r\n<option>藍色</option>', '在日本，御守是愿望的象征。御守最早用來辟邪和解除厄運，逐漸衍生到交通安全、安產、良緣、學業、健康等方面。現在，日本人尤其是女性每年都會購買更換御守，大家都用他來饋贈親朋以表達自己的祝愿，或是寄托希望、緩解壓力等等。所有商品百分百日本工藝，面料為日本京都名織物-金襴，手工精細，目前為止國內的廠家只能模仿花型及圖案，而金襴本身是無法模仿的哦。'),
(4, 'img/portfolio/a4.png', '求籤', '紀念品', '100', '<option>求籤</option>', '購買後可以前往求籤，進入解籤系統享有解籤資格。祝各位信徒們都可以心想事成，在籤詩中獲得救贖和希望解答。'),
(5, 'img/portfolio/b1.png', '線香', '佛具', '200', '<option>深紫色</option>\r\n<option>草綠色</option>', '・ 10厘米棒狀香。<br>\r\n・檀香的香氣柔和地散發出來，有一種清新餘韻。<br>\r\n※請使用香爐或不易燃的容器。<br>\r\n※處理火時要小心。即使在煙霧消失後，火種仍可能存在。<br>'),
(6, 'img/portfolio/b2.png', '刮痧板', '佛具', '180', '<option>黃金色</option>', '這座無教派的千年古寺，供奉著傳說中日本最古老的佛像「一光三尊阿弥陀如来像」，境內的本堂被指定為日本佛教建築國寶。而參拜完後，除了可以購買佛珠或御守回家之外，這裡還販售了寺方原創的「刮痧板」，透明的牛角形狀印上象徵善光寺的「善」字，兼具實用性與紀念性。'),
(7, 'img/portfolio/b3.png', '香皿', '佛具', '450', '<option>白色</option>', '香皿還重現了藥師寺東塔天花板的白鳳圖騰，精緻又具收藏價值。\r\n<br>* 燃燒時，是小心使用。\r\n<br>* 處理火時要小心。即使在煙霧消失後，火種仍可能存在。\r\n<br>* 瓷器小心易碎。'),
(8, 'img/portfolio/c1.png', '鳥居擺飾', '紀念品', '300', '<option>男人</option>\r\n<option>女人</option>\r\n<option>富士山</option>\r\n<option>鬼怪</option>\r\n<option>搖鈴</option>', '鳥居／とりい 是日本神社的建築之一，傳說是連接神明居住的神域與人類居住的俗世之通道，屬「結界」的一種。\r\n<br>鳥居有多種形狀，但大多均以兩根支柱與一至二根橫梁構成。 現在把鳥居成可擺飾的大小,\r\n<br>在日本或國外也都是受歡迎的紀念品, 如果將它們並排展示，那將是一個壯觀的景象。'),
(9, 'img/portfolio/c2.png', '佛珠', '紀念品', '650', '<option>綠色</option>\r\n<option>粉色</option>\r\n<option>藍色</option>', '此款佛珠自古以來即被視為避邪之聖物，其蘊藏著豐富的天然靈氣，有助於消除壓力、疲勞、濁氣等負面能量，也是友善、愛心以及希望的象徵。 無論是靜思冥想、唸經數珠時使用，或是隨身攜帶、掛置車上、家中神明配戴，都很合適，不僅十分漂亮還可以招來好福氣喔！'),
(10, 'img/portfolio/c3.png', '御守護太刀守', '紀念品', '650', '<option>金色</option>', '祀奉初代將軍德川家康的日光東照宮，寺境內的寶物館中，擁有2,000件藏品，其中兩把被列為國寶的太刀「銘助真」與「銘国宗」，尤其具有代表性。雖然這些寶物只能隔著櫥窗欣賞，但旅人們卻能夠把金色太刀造型的「御守護太刀守」買回家珍藏，當成擺設超有氣勢！');

-- --------------------------------------------------------

--
-- 資料表結構 `wish`
--

CREATE TABLE `wish` (
  `member_id` int(20) NOT NULL,
  `wish_content` varchar(10000) COLLATE utf8_unicode_ci NOT NULL,
  `wish_time` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- 傾印資料表的資料 `wish`
--

INSERT INTO `wish` (`member_id`, `wish_content`, `wish_time`) VALUES
(10001, '希望我可以賺大錢!!', '2022-05-11'),
(10002, '我要上台大', '2022-05-01'),
(10003, '可以順利找到工作', '2022-05-03'),
(10004, '平安健康順利', '2022-05-10'),
(10006, '希望可以順利找到好工作', '2022-05-05');

--
-- 已傾印資料表的索引
--

--
-- 資料表索引 `member`
--
ALTER TABLE `member`
  ADD PRIMARY KEY (`member_id`);

--
-- 資料表索引 `order`
--
ALTER TABLE `order`
  ADD PRIMARY KEY (`member_id`);

--
-- 資料表索引 `order_content`
--
ALTER TABLE `order_content`
  ADD PRIMARY KEY (`order_id`);

--
-- 資料表索引 `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`product_id`);

--
-- 資料表索引 `wish`
--
ALTER TABLE `wish`
  ADD PRIMARY KEY (`member_id`);

--
-- 在傾印的資料表使用自動遞增(AUTO_INCREMENT)
--

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `member`
--
ALTER TABLE `member`
  MODIFY `member_id` int(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10016;

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `order`
--
ALTER TABLE `order`
  MODIFY `member_id` int(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10007;

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `order_content`
--
ALTER TABLE `order_content`
  MODIFY `order_id` int(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `products`
--
ALTER TABLE `products`
  MODIFY `product_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=27;

--
-- 使用資料表自動遞增(AUTO_INCREMENT) `wish`
--
ALTER TABLE `wish`
  MODIFY `member_id` int(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10007;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
